import type { NextPage } from 'next';
import Head from 'next/head';
import { trpc } from '../utils/trpc';
import { BsCalendarWeekFill } from 'react-icons/bs';
import { FaRegUserCircle } from 'react-icons/fa';
import { RiRestaurant2Line } from 'react-icons/Ri';
import { MdOutlineSpaceDashboard } from 'react-icons/md';

const Home: NextPage = () => {
  const hello = trpc.useQuery([
    'example.hello',
    { text: 'from tRPC' },
  ]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta
          name="description"
          content="Generated by create-t3-app"
        />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Merriweather+Sans:ital,wght@0,300;0,500;1,300;1,400;1,500&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <main className="container flex min-h-screen p-4">
        <MiniNavBar></MiniNavBar>

        <EventCreation></EventCreation>
      </main>
    </>
  );
};

export default Home;

const EventCreation = () => {
  return (
    <div className="flex flex-col items-center justify-center mx-auto">
      <div>Create Event</div>
      <div>
        <div>Title</div>
        <input
          type="text"
          name=""
          id=""
          className="border rounded-lg "
        />
      </div>
    </div>
  );
};

const MiniNavBar = () => {
  return (
    <div className="border-2 rounded-lg w-28">
      <div className="flex flex-col items-center justify-center px-3 pt-4 space-y-4 text-center">
        <div>Bikini Bottom</div>
        <div>
          <MdOutlineSpaceDashboard
            size={30}
          ></MdOutlineSpaceDashboard>
        </div>
        <div className="">
          <FaRegUserCircle size={30}></FaRegUserCircle>
        </div>
        <div>
          <BsCalendarWeekFill size={30}></BsCalendarWeekFill>
        </div>
        <div>
          <RiRestaurant2Line size={30}></RiRestaurant2Line>
        </div>
      </div>
    </div>
  );
};

const NavBar = () => {
  return (
    <div className="border-2 rounded-lg w-96">
      <div className="flex flex-col justify-start pt-4 pl-5 space-y-4">
        <div className="flex">
          <MdOutlineSpaceDashboard
            size={30}
          ></MdOutlineSpaceDashboard>
          <div className="pl-3">Dashboard</div>
        </div>
        <div className="flex">
          <FaRegUserCircle size={30}></FaRegUserCircle>
          <div className="pl-3">First Name, Last Name</div>
        </div>

        <div className="pt-10">
          <div className="items-center text-center">Events</div>
          <div className="flex">
            <BsCalendarWeekFill size={30}></BsCalendarWeekFill>
            <div className="pl-3">Calendar</div>
          </div>
          <div className="flex">
            <RiRestaurant2Line size={30}></RiRestaurant2Line>
            <div className="pl-3">Restaurants</div>
          </div>
        </div>
      </div>
    </div>
  );
};

// type TechnologyCardProps = {
//   name: string;
//   description: string;
//   documentation: string;
// };

const TechnologyCard = ({
  name,
  description,
  documentation,
}: TechnologyCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <a
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </a>
    </section>
  );
};
